apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: catalog-writers
  description: Catalog writers
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: catalog-writer@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: AndrienkoAleksandr
spec:
  profile:
    # Intentional no displayName for testing
    email: oandriie@redhat.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [catalog-writers]
---
