apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: managers
  description: managers
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: manager@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---