apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  # parent: backstage
  children: [ backstage ]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: AndrienkoAleksandr
spec:
  profile:
    # Intentional no displayName for testing
    email: oandriie@redhat.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Logarifm
  annotations:
   'bitbucket.org/username': 'Logarifm'
spec:
  profile:
   # Intentional no displayName for testing
    email: logarifm6@gmail.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning
spec:
  profile:
    displayName: Nigel Manning
    email: nigel-manning@example.com
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [team-a]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [team-a]
