---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-for-jfrog-artifactory
  description: Storage subsystem of the Wayback Archive
  annotations:
    'jfrog-artifactory/image-name': 'hello-world'
spec:
  type: service
  lifecycle: production
  owner: team-a
