apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive-storage
  description: Storage subsystem of the Wayback Archive
  annotations:
    "backstage.io/kubernetes-namespace": test
spec:
  type: service
  lifecycle: production
  owner: team-a
  subcomponentOf: wayback-archive
